language: php

php: 
  - 5.3
  - 5.4

env:
  global:
    - CI_HOME=`pwd`/odi86/kort
    - DEPLOY="true"
    - BUILD_DIR=`pwd`/build_heroku 
    - secure: "EIn+Rm7OxX8OKygBRBCaSTOqFGcBMWu5kHdKqSxOmHRJYjxuMOJpKV+rnyep\n+RsyFDx2Z9yKlqRRS4cpZh7M6wwC63EV46+7aWtzzTjnbMZfVzLQA9EmaEU4\nYMsKGtpQk2mhvaNKd3UbEpDl0Zq74NnAY0zipx0l02UymcFnZEc=" 
    - secure: "cOmMBP4UyklRC0nfeTZsX/NV4GhMBT+AntUmlWxXS5Rj2yrNcmNc7320gNm5\nCLSVRYyk7/8feyUEMznWrUn/62htZp0tEBAWtXg86dgIZgH4HPy9l2pKuSsH\nxZTHgjUJI7JOuyLG4ID9D5maVLE35UWag/NEtcRVy5QXLZOrs0M="
  matrix:
    - TARGET_ENV="dev"
    - TARGET_ENV="prod"

before_script:
  - gem install sass
  - gem install compass
  - gem install jsduck
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh >/dev/null 2>&1
  - sudo npm install -g grunt >/dev/null 2>&1
  - curl -s http://getcomposer.org/installer | php --
  - php composer.phar install --dev
  - sudo pear channel-discover pear.phpdoc.org
  - sudo pear install phpdoc/phpDocumentor-alpha
  - sudo apt-get install graphviz
  - export PATH="$PATH:$CI_HOME:/usr/local/heroku/bin"
  - mv $CI_HOME/server/php/Webservice/Database/DbConfig.example.php $CI_HOME/server/php/Webservice/Database/DbConfig.php
  - phpenv rehash

script: ant -f build_kort.xml build

after_script:
  - bash $CI_HOME/server/heroku/heroku.sh
