language: php

php:
  - "5.4"
  - "5.3"

env:
  - DEPLOY=true
  - DEPLOY=false
  global:
    - BUILD_DIR=`pwd`/build_heroku 
    - CI_HOME=`pwd`/odi86/kort
    - secure: "cOmMBP4UyklRC0nfeTZsX/NV4GhMBT+AntUmlWxXS5Rj2yrNcmNc7320gNm5\nCLSVRYyk7/8feyUEMznWrUn/62htZp0tEBAWtXg86dgIZgH4HPy9l2pKuSsH\nxZTHgjUJI7JOuyLG4ID9D5maVLE35UWag/NEtcRVy5QXLZOrs0M="

matrix:
  exclude:
    - php: "5.3"
      env: DEPLOY=true
    - php: "5.4"
      env: DEPLOY=false

before_script:
  - gem install sass
  - gem install compass
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh >/dev/null 2>&1
  - sudo npm install -g grunt >/dev/null 2>&1
  - wget https://raw.github.com/wandernauta/yuml/master/yuml && chmod +x yuml
  - pear install PHP_CodeSniffer && phpenv rehash
  - sudo pear channel-discover pear.survivethedeepend.com
  - sudo pear channel-discover hamcrest.googlecode.com/svn/pear
  - sudo pear install --alldeps deepend/Mockery
  - export PATH="$PATH:$CI_HOME:/usr/local/heroku/bin"

script: ant -f build_kort.xml build

# heroku part from https://gist.github.com/443c00fe346045522db7
after_script:
  - yes | ruby $CI_HOME/server/travis_deployer.rb
  - bash $CI_HOME/server/heroku/heroku_keys.sh
  - bash $CI_HOME/server/heroku/heroku_build.sh
  - cd $BUILD_DIR
  - bash $CI_HOME/server/heroku/heroku_add.sh >/dev/null
  - bash $CI_HOME/server/heroku/heroku_push.sh
