env:
  global:
    - secure: "cOmMBP4UyklRC0nfeTZsX/NV4GhMBT+AntUmlWxXS5Rj2yrNcmNc7320gNm5\nCLSVRYyk7/8feyUEMznWrUn/62htZp0tEBAWtXg86dgIZgH4HPy9l2pKuSsH\nxZTHgjUJI7JOuyLG4ID9D5maVLE35UWag/NEtcRVy5QXLZOrs0M="

before_script:
  - gem install sass

script: ant build

# heroku part from https://gist.github.com/443c00fe346045522db7
after_script:
  - yes | ruby travis_deployer.rb
  - git checkout -b travis
  - git rm .gitignore
  - git add .
  - git status
  - git commit -m "Travis CI commit of files added/modified from build"
  - gem install heroku
  - heroku keys:clear
  - yes | heroku keys:add
  - git push heroku travis:master
