language: php

env:
  global:
    - BUILD_DIR=`pwd`/build_heroku 
    - CI_HOME=`pwd`/odi86/kort
    - secure: "cOmMBP4UyklRC0nfeTZsX/NV4GhMBT+AntUmlWxXS5Rj2yrNcmNc7320gNm5\nCLSVRYyk7/8feyUEMznWrUn/62htZp0tEBAWtXg86dgIZgH4HPy9l2pKuSsH\nxZTHgjUJI7JOuyLG4ID9D5maVLE35UWag/NEtcRVy5QXLZOrs0M="

before_script:
  - gem install sass
  - gem install compass
  - gem install heroku
  - sudo npm install -g grunt >/dev/null 2>&1

script: ant -f build_kort.xml build

# heroku part from https://gist.github.com/443c00fe346045522db7
after_script:
  - yes | ruby $CI_HOME/server/travis_deployer.rb
  - bash $CI_HOME/server/heroku/heroku_keys.sh
  - bash $CI_HOME/server/heroku/heroku_build.sh
  - cd $BUILD_DIR
  - bash $CI_HOME/server/heroku/heroku_add.sh 
  - bash $CI_HOME/server/heroku/heroku_push.sh
